controller_frequency: 10.0
TrajectoryPlannerROS:
  max_vel_x: 0.50
  min_vel_x: 0.10
  max_rotational_vel: 0.8
  min_in_place_rotational_vel: 0.3
  max_vel_theta: 0.6
  min_vel_theta: -0.6
  min_in_place_vel_theta: 0.3
  acc_lim_th: 1.0
  acc_lim_x: 1.0
  acc_lim_y: 1.0

  holonomic_robot: false
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.3
  goal_distance_bias: 24
  path_distance_bias: 32
# occdist_scale: 10.2
  latch_xy_goal_tolerance: false
  min_turning_radius: 0.0
  pdist_scale: 11.8
  g_dist: 0.6
  occdist_scale: 0.1

  heading_lookahead: 0.325
 
  oscillation_reset_dist: 0.05

  vx_samples: 6
  vtheta_samples: 20
  dwa: false

  meter_scoring: true
  recovery_behavior_enabled: false
  clearing_rotation_allowed: false
